### ISSUE TITLE
Correctly using get<T> to get RoomPosition from creep memory.

### ISSUE THREAD

**Issue by WooterTheTroubleshooter** [daboross/screeps-in-rust-via-wasm#159]
So, I am trying to use the set<T> and get<T> methods to store and retrieve a screeps::RoomPosition to memory, but I'm not entirely sure how to correctly use this.

```
match creep.memory().get<screeps::RoomPosition>("target")
{
    Ok(target) => move_to(target),
    Err(_) => warn!("Something went wrong trying to get target from creep")
}
```
Is this the correct way to go use this method?

_Originally posted by @WooterTheTroubleshooter in https://github.com/daboross/screeps-in-rust-via-wasm/issues/95#issuecomment-508999581_

**Comment by daboross** [comment]
I think this is the syntax you're looking for:
```rust
match creep.memory().get::<screeps::RoomPosition>("target")
{
    Ok(target) => move_to(target),
    Err(_) => warn!("Something went wrong trying to get target from creep")
}
```

using the turbofish `::<T>` to specify the type you want out. 

---

With that said, I don't believe this will work since in memory, a `RoomPosition` will no longer be a `RoomPosition` but just a plain object. I'd recommend using a `LocalRoomPosition`, which brings all info over to the Rust side, and just gets properties rather than checking if the thing is actually a `RoomPosition`. I believe the following should work:

```rust
match creep.memory().get::<screeps::LocalRoomPosition>("target")
{
    Ok(target) => move_to(target),
    Err(_) => warn!("Something went wrong trying to get target from creep")
}
```

**Comment by WooterTheTroubleshooter** [comment]
Ok, thank you. The turbofish seems to do the trick. I was expecting it to be the same syntax as the documentation.

I don't really see the exact reason `LocalRoomPosition` is needed yet, but I'm sure I'll run into problems with it soon enough.

After re-reading the documentation and the code sample I had created for describing this issue, I have found that the `get<T>` has a different return signature than the others. All the other memory accessors return a `Result<Option<T>, ConversionError>`. What happens with `get<T>` when the value is undefined or null?

Looking into the source, the code is almost the same for the fixed type accessors.
```
   pub fn i32(&self, key: &str) -> Result<Option<i32>, ConversionError> {
       (js! {                                                            
           return (@{self.as_ref()})[@{key}];                            
       })                                                                
       .try_into()                                                       
   } 

   pub fn get<T>(&self, key: &str) -> Result<T, ConversionError>
   where                                                        
       T: TryFrom<Value, Error = ConversionError>,              
   {                                                            
       (js! {                                                   
           return (@{self.as_ref()})[@{key}];                   
       })                                                       
                                                                
       .try_into()                                              
   }                                                                                                                           
```

Does that mean I should actually use `get::<Option<screeps::LocalRoomPosition>>`?

```
match creep.memory().get::<Option<screeps::LocalRoomPosition>>("target")
{
    Ok(target) => match target 
   {
        Some(target) => move_to(target),
        None => move_to(get_target_for_action(creep))
    }
    Err(_) => warn!("Something went wrong trying to get target from creep")
}
```

**Comment by daboross** [comment]
Ah! Yeah, I think using `Option<LocalRoomPosition>` sounds like a good idea.

If you call `get::<LocalRoomPosition>` and it isn't there, you'll get an `Err` result (since `undefined` is not a `LocalRoomPosition`). 

Improving documentation on using this (and many other things) is definitely a good idea! Most of this crate_works_, and what docs there are should be correct, but at times it can seem thrown together in a "if you know how to use it, you can" sort of way.

With `RoomPosition` vs. `LocalRoomPosition`, the problem is that when storing any game objects in memory, type information is erased. Javascript AIs also run into this problem, so there's some good general documentation on the screeps website. Most or all of https://docs.screeps.com/global-objects.html#Storing-game-objects-in-memory applies to these API bindings - `LocalRoomPosition` kind of works around the issue by not being or requiring any type in JavaScript.

**Comment by WooterTheTroubleshooter** [comment]
Ok, after reading into it some more I think I see the issue. Essentially I should only store the neccesary structs and recreate objects when I need their behaviors.

However when using Option<LocalRoomPosition> in the get<T> I get the following error.
```
match creep.memory().get::<Option<screeps::LocalRoomPosition>>("target")
{ ... }

[rustc] the trait bound `screeps::LocalRoomPosition: std::convert::AsRef<stdweb::Reference>` is not satisfied                                                                                                                                                                 
                                                                                
the trait `std::convert::AsRef<stdweb::Reference>` is not implemented for `screeps::LocalRoomPosition`
                                                                                
note: required because of the requirements on the impl of `screeps::traits::TryFrom<stdweb::Value>` for `std::option::Option<screeps::LocalRoomPosition>`
```
When getting the LocalRoomPosition without Option it does seem to compile, will I get an error when 'target' is null?

**Comment by daboross** [comment]
Oh - that's an issue with this repo's implementations! We should fix that.

Thanks for helping us actually test this! Apologies for not having memory _completely_ worked out.

**Comment by daboross** [comment]
For context, while we implemented this memory API, I haven't really been using it much. Instead mostly I've just been using `serde_derive` in combination with either some other serialization (like `serde_json`) for segment memory, or `js_deserializable!()` / `js_serializable!()` for `Memory`.

I believed `Option<LocalRoomPosition>` would work, but apparently there are some type constraints which prevent that from actually passing type checking.

I'm thinking adding `get_opt<T>(&str) -> Result<Option<T>, ...>` and `exists(&str)` methods would be better for this if we can't get `Option<X>` to work for non-reference-type `X`s like `LocalRoomPosition`. @ASalvail any thoughts?

**Comment by ASalvail** [comment]
I've always wondered why we even have `LocalRoomPosition`. It somewhat clashes with all our other object implementations. I never actually had a look into it since I figured I'd get there once I actually need it (like @WooterTheTroubleshooter :P ) 

Couldn't we make `LocalRoomPosition` a `ReferenceType`?
Otherwise, sure, we can add a `get_opt`, but I would try to find a better long-term solution.

**Comment by ASalvail** [comment]
@WooterTheTroubleshooter You should be able to do 
`creep.memory().get::<Option<screeps::RoomPosition>>("target").local()` to get a `LocalRoomPosition`.

**Comment by daboross** [comment]
The main reason I wanted it was for a common thing for performance - positions just felt like something which really should be "plain data", and should be easy to copy around and manipulate in rust code without any calls to JavaScript. It is kind of out-of-place in that there aren't many other non-constant things which can exist without referencing JS, though.

The problem with this particular issue is that `RoomPosition` or having `LocalRoomPosition` be a `ReferenceType` (referencing `RoomPosition`) won't work either, because once things are stored in `Memory` and a tick passes, they loose all type information, and we typecheck things we retrieve using that same type information.

**Comment by ASalvail** [comment]
Just saw that @daboross believed it wouldn't work: if it really doesn't: _that_'s a bug.

**Comment by daboross** [comment]
I'd argue it's a design decision in screeps itself?

Like, as soon as you put things in `Memory`, they become plain-data. Next tick, it _isn't a `RoomPosition` at all_.

**Comment by ASalvail** [comment]
Ah, I get what you mean now... Then we need an implementation from `Value` to `RoomPosition` (and/or `LocalRoomPosition`.

**Comment by ASalvail** [comment]
... should we force users to use serde for serialization? Emulate `Memory`'s behavior (deserialize on first access), but using `serde` instead?

**Comment by daboross** [comment]
Do we expect users to really store anything else in memory which has an actual JavaScript type besides `RoomPosition`?

If they store/retrieve plain values, it'll succeed trivial because those types persist through JSON. For `js_deserializable!()` values, deserialization can succeed because stdweb won't expect there to be a corresponding JavaScript type. Most other types, `Creep`, `StructureSpawn`, etc., will trivial fail to be stored in memory anyways because they're live game objects. Users will just store ids instead.

**Comment by daboross** [comment]
@ASalvail and I talked more in the slack chat, and decided to go with changing `get` and `get_path` to return `Option<T>` rather than `T`.

This PR should make `memory.get::<LocalRoomPosition>("target")` work correctly.

---

I tried some more things and realized `memory.set("target", local_room_pos)` isn't working, so... going to try to fix that too.

**Comment by WooterTheTroubleshooter** [comment]
So I did not realize when getting a `RoomPosition` I was actually calling the javascript api and actually getting results in JavaScript.

However after reading all the comments, why does `RoomPosition` not have the 3 properties/fields the JavaScript roomposition does have?
```
struct RoomPosition {
    room_name: string,
    x: u32,
    y: u32
}
```
Could it be possible to just store that struct trough a serializer and when getting it the following tick, deserialize and coerce it into the same type?

I mean, I am asking for a `RoomPosition` so it's easy to just match the fields of the plain object with the type I am referencing in the `get<Option<T>>`?

---

After reading through the `x()` and `y()` methods on the rust side of the api, I now understand that is exactly what has been done with the `LocalRoomPosition` as `RoomPosition` is actually a wrapper to a reference in JavaScript.

To be honest, I was expecting to get rust copies of objects, not actual references to objects living in JavaScript.

Thanks for all the clarification, I am awaiting the latest changes.

**Comment by ASalvail** [comment]
The philosophy so far has been to avoid copying js objects in rust as much as possible by only keeping track of a reference to a js object (anything that implements `AsRef`, basically). If we wanted to get a copy, what should we copy? Everything would be wasteful most of the time...
That's why, for instance, there are no `Creeps` struct with a copy of everything there is to know about a creep: it would force us to copy it entirely and this is quite costly.

`RoomPosition` is slightly different: it makes sense to get a local copy since it's actually not a js object. (Well, it is, but it doesn't have an id, which makes dealing with it a bit different). To account for that, there is `LocalRoomPosition` which @daboross made very efficient (if unfriendly).

Nothing prevents you from making your own `Creep` struct that would act as a copy, but keep in mind that even with the IVM, any js object that has an `id` is deleted every tick.

So, to solve your problem, you should request a `LocalRoomPosition`, bearing in mind that when you need to pass a `RoomPosition` to js, you'll need to call `.remote()` first.

Does that make sense?

For `get<T>`, you only need to implement `TryFrom<Value> for T`. `Value` is basically any js object 
https://docs.rs/stdweb/0.4.18/stdweb/enum.Value.html
and the easiest way to implement it is to make your struct/enum use `#[derive(Serialization, Deserialization)]` from the `serde` crate ( http://serde.rs for more info) and apply the `js_[de]serialization!` on your struct.

**Comment by WooterTheTroubleshooter** [comment]
Thank you, I really did not connect the dots on the way the webassembly connects with JavaScript and just expected to access stuff as if it were rust objects.

I look forward to the changes.
