### ISSUE TITLE
No way to access stdweb's `ConversionError`

### ISSUE THREAD

**Issue by ASalvail** [daboross/screeps-in-rust-via-wasm#39]
Most of `stdweb` conversion return a `ConversionError` when it fails. The problem with this is that the struct is kept private. Admittedly, it is exposed (but hidden) through `stdweb::private`, however, this is not really a fix as we would still have problems with [associated types not resolving to concrete types](https://github.com/rust-lang/rust/issues/34430).

My suggestion would be to define a `ConversionError` owned by out lib that would box over `stdweb`'s own `ConversionError`. This would remove a lot of headaches due to associated type.

**Comment by daboross** [comment]
For some of the situations it might be possible to create our own type alias without wrapping `stdweb::webcore::ConversionError`, something like:

```rust
pub type ConversionError = <i32 as TryFrom<Value>>::Error
```

**Comment by ASalvail** [comment]
We could simplify a lot I suppose by returning a trait object implementing `std::error::Error` and just be done with it... 
My problems now are:
- I can't construct the `ConversionError` (have to do my checks in JS)
- I can't append another, let's say, `ReferenceError` without dropping or boxing the  `ConversionError`.
- It's generally a pain to work with the associated types.

**Comment by daboross** [comment]
Ah, hm. I hadn't thought of the possibility of doing checks outside of JS.

One thing that might help here is `stdweb_derive`'s [`#[derive(ReferenceType)]`](https://docs.rs/stdweb-derive/0.5.0/stdweb_derive/fn.derive_reference_type.html). It might be able to do checks for us if we `#[derive(ReferenceType)] #[reference(instance_of = "Creep")]` - I vague remember explicitly not choosing to use this since it did checks, but if we have a way to construct the value outside of TryFrom it might be more reasonable. Have you looked at this at all, and do you think it might alleviate the pain of working with `ConversionError` by it just doing everything?

Above might be a bit off-topic, but I don't know if we have a particularly on-topic issue for discussing this.

**Comment by daboross** [comment]
CC https://github.com/koute/stdweb/issues/280.
