### ISSUE TITLE
Output of cargo-screeps 0.2 isn't colorized

### ISSUE THREAD

**Issue by ASalvail** [daboross/screeps-in-rust-via-wasm#41]
The output of `cargo screeps build` lose the color from `cargo build`.

**Comment by daboross** [comment]
Hm, it seems to be retaining color on my machine.

![my 'cargo screeps build' output](https://user-images.githubusercontent.com/1152146/45590947-886ccf80-b8f9-11e8-95ab-4745365a4e43.png)

I don't believe anything should have changed with the code calling into `cargo build` since the last version. Any chance something else has changed in your environment?

**Comment by ASalvail** [comment]
I guess VSCode is just lazy. It's back to normal now. Closing.
